service: import-service

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::products-s3-csv/*"

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

functions:
  importProductsFile:
    handler: app/handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                filename: true
  importFileParser:
    handler: app/handler.importFileParser
    events:
      - s3:
          bucket: products-s3-csv
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: uploaded/
            - suffix: .csv
